---
title: "Technical Guideline Series"
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
    toc_float: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Invasive Alien Species Assessment Map

**Prepared by Renske Gudde - TSU for knowledge and data** 
  
**Reviewed by Aidin Niamir - Head of the Technical Support
Unit of Knowledge and Data**

*For any inquires please contact
[aidin.niamir\@senckenberg.de](mailto:aidin.niamir@senckenberg.de)*

Version: 1.3   
Last Updated: 18th of April, 2024

DOI: [10.5281/zenodo.10103271](https://doi.org/10.5281/zenodo.10103271)

This page is designed to help navigate through all the documents of the invasive alien species assessment, such as the data management reports, figures and all accompanying documents.

## Table of content
1. [Full report](#FullReport)
2. [Summary for policymakers](#SPM)
3. [Factsheets](#Factsheets)
4. [Chapter 1](#Ch1)
5. [Chapter 2](#Ch2)
6. [Chapter 3](#Ch3)
7. [Chapter 4](#Ch4)
8. [Chapter 5](#Ch5)
9. [Chapter 6](#Ch6)
10. [Glossary](#Glossary)
11. [Underlying bibliographic data and research materials](#Library)

#### <a id="FullReport"></a>Full report
[Full report](https://doi.org/10.5281/zenodo.7430682)

[Data management report for scenarios and models liaison](https://doi.org/10.5281/zenodo.5706520)

[Data management report for cross-chapter literature review on Indigenous Peoples and local communities and invasive alien species](https://doi.org/10.5281/zenodo.5760266)

#### <a id="SPM"></a>Summary for policymakers
[SPM](https://doi.org/10.5281/zenodo.7430692)

[The figures, tables and captions used in the SPM](https://doi.org/10.5281/zenodo.8045527)

#### <a id="Factsheets"></a>Factsheets

[Factsheet 1 - Invasive aline species: data on trends and impacts](https://zenodo.org/doi/10.5281/zenodo.10057013)

[Factsheet 2 - The role of businesses in the management and governance of biological invasion](https://zenodo.org/doi/10.5281/zenodo.10057025)

[Factsheet 3 - Invasive alien species affect protected areas and most natural ecosystems](https://zenodo.org/doi/10.5281/zenodo.10057029)

[Factsheet 4 - Biological invasions on islands](https://zenodo.org/doi/10.5281/zenodo.10057031)

[Factsheet 5 - Invasive alien species management and governance](https://zenodo.org/doi/10.5281/zenodo.10057035)

[Factsheet 6 - Biological invasions and stakeholder engagement](https://zenodo.org/doi/10.5281/zenodo.10057037)

[Factsheet 7 - Climate change and biological invasions](https://zenodo.org/doi/10.5281/zenodo.10408375)

#### <a id="Ch1"></a>Chapter 1. Introducing biological invasions and the IPBES thematic assessment of invasive alien species and their control
[Chapter 1](https://doi.org/10.5281/zenodo.7430723)

[Figures, tables and captions](https://doi.org/10.5281/zenodo.8041593)

[Data management report for Table 1.3 and supplementary material 1.4](https://doi.org/10.5281/zenodo.5518254)

[Data management report for Figure 1.2](https://doi.org/10.5281/zenodo.7560099)

#### <a id="Ch2"></a>Chapter 2. Trends and status of alien and invasive alien species
[Chapter 2](https://doi.org/10.5281/zenodo.7430725)

[Figures, tables, captions and data management reports](https://doi.org/10.5281/zenodo.7615582)

#### <a id="Ch3"></a>Chapter 3. Drivers affecting biological invasions
[Chapter 3](https://doi.org/10.5281/zenodo.7430727)

[Figures, tables and captions](https://doi.org/10.5281/zenodo.8045887)

[List of literature and associated data management reports](https://doi.org/10.5281/zenodo.5529309)

[Data management report for Figure 3.5](http://doi.org/10.5281/zenodo.7861123)

[Data management report for Figure 3.16](http://doi.org/10.5281/zenodo.7861139)

#### <a id="Ch4"></a>Chapter 4. Impacts of invasive alien species on nature, nature's contributions to people, and good quality of life
[Chapter 4](https://doi.org/10.5281/zenodo.7430731)

[Figures, tables and captions](https://doi.org/10.5281/zenodo.8046326)

[Impact evidence database](https://doi.org/10.5281/zenodo.5706616)

[Data management report for the impact evidence database](https://doi.org/10.5281/zenodo.5766069)

[Data management report for Figure 4.5](https://doi.org/10.5281/zenodo.5762737)

[Data management report for Figure 4.25 and figure SPM 3.b](https://doi.org/10.5281/zenodo.7857828)

[Data management report for Figure 4.27](https://doi.org/10.5281/zenodo.8231570)

#### <a id="Ch5"></a>Chapter 5. Management; challenges, opportunities and lessons learned
[Chapter 5](https://doi.org/10.5281/zenodo.7430733)

[Figures, tables and captions](https://doi.org/10.5281/zenodo.8046424)

[Data management report for Figure 5.24](https://doi.org/10.5281/zenodo.7858651)


#### <a id="Ch6"></a>Chapter 6. Governance and policy options for the management of biological invasions
[Chapter 6](https://doi.org/10.5281/zenodo.7430747)

[Figures, tables and captions](https://doi.org/10.5281/zenodo.8046442)

[Data management report for assessing invasive alien species governance options](https://doi.org/10.5281/zenodo.5762739)

[Data management report table of knowledge and data gaps](https://doi.org/10.5281/zenodo.7840018)

#### <a id="Glossary"></a>Glossary
[IAS glossary](https://zenodo.org/doi/10.5281/zenodo.10990924)

#### <a id="Library"></a>Underlying bibliographic data and research materials
[IAS Zotero library](https://www.zotero.org/groups/2352922/ipbes_invasive_alien_species_assessment)